services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: eduplus-auth
    env_file:
      - ./services/auth-service/.env
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  course-service:
    build:
      context: ./services/course-service
      dockerfile: Dockerfile
    container_name: eduplus-course
    env_file:
      - ./services/course-service/.env
    ports:
      - "5003:3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eduplus-front
    depends_on:
      - auth-service
      - course-service
    ports:
      - "8080:80"
