services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: eduplus-auth
    env_file:
      - ./services/auth-service/.env
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  course-service:
    build:
      context: ./services/course-service
      dockerfile: Dockerfile
    container_name: eduplus-course
    env_file:
      - ./services/course-service/.env
    ports:
      - "5003:3001"

  evaluation-service:
    build:
      context: ./services/evaluation-service
      dockerfile: Dockerfile
    container_name: eduplus-evaluation
    depends_on:
      - auth-service
      - course-service
    env_file:
      - ./services/evaluation-service/.env
    environment:
      - PORT=5005
    ports:
      - "5005:5005"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eduplus-front
    depends_on:
      - auth-service
      - course-service
      - evaluation-service
    ports:
      - "8080:80"
